version: 2.1
orbs:
  snyk: snyk/snyk@1.1.0
workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - snyk/scan
